name: Wake Up Render

on:
  schedule:
    # Cada 10 minutos
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Up APIs
        run: |

          echo "Despertando Tienda Vicky..."
          curl -L --fail https://app-tienda-vicky.onrender.com

          echo "Despertando App Combustible..."
          curl -L --fail https://app-combustible.onrender.com

          echo "Despertando App Combustible..."
          curl -L --fail https://app-ferreteria-iziy.onrender.com
          
          echo "Todas las APIs fueron consultadas."